project:
  type: website
lang: es
website:
  title: "Proyectos Maestría en Ciencia Agropecuarias"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yudicf
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


